        #!/bin/bash
        set -u
        set -o pipefail

        # macOS App Inventory
        # Maintained directly — no longer generated by app_inventory.py.
        # READ-ONLY: no file writes, no temp files, no cleanup.
        # All output to stdout. Deploy via MDM; framework captures output.

        # ── Jamf / MDM environment hardening ─────────────────────────────────
        # Jamf runs scripts as root with a minimal environment.  set -u will
        # abort on any unset variable, so we must provide safe defaults.
        PATH="${PATH:-/usr/bin:/bin:/usr/sbin:/sbin}"

        INCLUDE_SYSTEM_APPS="${INCLUDE_SYSTEM_APPS:-0}"
        INCLUDE_EXTERNAL_VOLUMES="${INCLUDE_EXTERNAL_VOLUMES:-0}"
        WITH_HOMEBREW="${WITH_HOMEBREW:-0}"
        WITH_CHROME_EXTENSIONS="${WITH_CHROME_EXTENSIONS:-0}"
        WITH_APP_SCAN="${WITH_APP_SCAN:-1}"
        WITH_FIND_SCAN="${WITH_FIND_SCAN:-1}"
        FIND_TIMEOUT="${FIND_TIMEOUT:-30}"
        PROFILER_TIMEOUT="${PROFILER_TIMEOUT:-30}"
        WITH_NICE="${WITH_NICE:-0}"
        QUIET="${QUIET:-1}"

        # Compact inventory defaults. PATH_DENYLIST_EXTRA can append one
        # glob pattern per line without modifying the script.
        PATH_DENYLIST_DEFAULT="
"
        PATH_DENYLIST_EXTRA="${PATH_DENYLIST_EXTRA:-}"

        # ── Command helpers ───────────────────────────────────────────────────

        timeout_run() {
          local seconds="$1"
          shift

          if [ -x /opt/homebrew/bin/gtimeout ]; then
            /opt/homebrew/bin/gtimeout "$seconds" "$@"
          elif [ -x /usr/local/bin/gtimeout ]; then
            /usr/local/bin/gtimeout "$seconds" "$@"
          elif command -v timeout >/dev/null 2>&1; then
            timeout "$seconds" "$@"
          else
            "$@"
          fi
        }

        # ── CSV helpers ──────────────────────────────────────────────────────

        csv_escape() {
          local s="${1:-}"
          s=${s//\"/\"\"}
          printf '\"%s\"' "$s"
        }

        csv_row() {
          local first=1 field
          for field in "$@"; do
            if [ "$first" -eq 1 ]; then first=0; else printf ','; fi
            csv_escape "$field"
          done
          printf '\n'
        }

        # ── Plist / path helpers ─────────────────────────────────────────────

        plist_get() {
          /usr/libexec/PlistBuddy -c "Print :$2" "$1" 2>/dev/null || true
        }

        plist_status() {
          local plist="$1"
          [ -e "$plist" ] || { printf 'M'; return 0; }
          [ -f "$plist" ] || { printf 'E'; return 0; }
          [ -r "$plist" ] || { printf 'R'; return 0; }
          /usr/bin/plutil -lint "$plist" >/dev/null 2>&1 || { printf 'P'; return 0; }
          printf ''
        }

        canonical_dir() {
          ( cd "$1" 2>/dev/null && /bin/pwd -P ) || true
        }

        join_lines() {
          local first="${1:-}" second="${2:-}"
          if [ -n "$first" ] && [ -n "$second" ]; then
            printf '%s\n%s\n' "$first" "$second"
          elif [ -n "$first" ]; then
            printf '%s\n' "$first"
          elif [ -n "$second" ]; then
            printf '%s\n' "$second"
          fi
        }

        path_matches_patterns() {
          local path="$1" patterns="$2" pattern
          [ -n "$path" ] || return 1
          while IFS= read -r pattern; do
            [ -n "$pattern" ] || continue
            case "$path" in
              $pattern) return 0 ;;
            esac
          done <<EOF
$patterns
EOF
          return 1
        }

        path_is_denylisted() {
          local patterns
          patterns="$(join_lines "$PATH_DENYLIST_DEFAULT" "$PATH_DENYLIST_EXTRA")"
          [ -n "$patterns" ] || return 1
          path_matches_patterns "$1" "$patterns"
        }

        to_epoch() {
          local raw="${1:-}" epoch=""
          [ -n "$raw" ] || return 0
          case "$raw" in
            "(null)"|*"could not find"*) return 0 ;;
          esac

          epoch="$(/bin/date -j -f '%Y-%m-%d %H:%M:%S %z' "$raw" '+%s' 2>/dev/null || true)"
          [ -n "$epoch" ] || epoch="$(/bin/date -j -f '%Y-%m-%d %H:%M:%S %Z' "$raw" '+%s' 2>/dev/null || true)"
          [ -n "$epoch" ] || epoch="$(/bin/date -d "$raw" '+%s' 2>/dev/null || true)"
          printf '%s' "$epoch"
        }

        # ── Bundle validation ────────────────────────────────────────────────

        is_valid_app_bundle() {
          # Returns 0 (valid) for any .app directory that has Info.plist.
          # We intentionally do NOT require CFBundleExecutable to exist
          # or be executable — some apps use non-standard structures
          # (script wrappers, symlinked executables, etc.) and we'd rather
          # over-report than silently miss a risk app.
          local app="$1"
          [ -d "$app" ] || return 1
          case "$app" in *.app) ;; *) return 1 ;; esac

          # Info.plist is the minimum bar — without it, it's not an app bundle
          [ -f "$app/Contents/Info.plist" ] || return 1
          return 0
        }

        is_nested_app() {
          case "$1" in
            *.app/Contents/*) return 0 ;;
            *.app/Versions/*) return 0 ;;
            *) return 1 ;;
          esac
        }

        is_noisy_path() {
          local app="$1"
          # Resolve APFS firmlink prefix so /System/Volumes/Data/Users/...
          # is evaluated as /Users/... instead of being blanket-dropped.
          case "$app" in /System/Volumes/Data/*) app="/${app#/System/Volumes/Data/}" ;; esac

          case "$app" in
            # True system internals — not user-installed apps
            /System/Volumes/*) return 0 ;;
            /private/var/*|/private/tmp/*|/tmp/*) return 0 ;;
            */.Trash/*) return 0 ;;
          esac
          if [ "$INCLUDE_EXTERNAL_VOLUMES" != "1" ]; then
            case "$app" in /Volumes/*) return 0 ;; esac
          fi
          return 1
        }

        should_emit_app() {
          local discovered_app="$1" app="$2" plist bundle_id
          is_nested_app "$app" && return 1
          is_noisy_path "$discovered_app" && return 1
          path_is_denylisted "$discovered_app" && return 1
          plist="$app/Contents/Info.plist"
          bundle_id="$(plist_get "$plist" CFBundleIdentifier)"

          if [ "$INCLUDE_SYSTEM_APPS" != "1" ]; then
            case "$discovered_app" in
              /System/Applications/*|/System/Library/*) return 1 ;;
            esac
            case "$bundle_id" in com.apple.*) return 1 ;; esac
          fi
          return 0
        }

        # ── Candidate collection (stdout only, no temp files) ────────────────
        #
        # ADVERSARIAL DESIGN: This script is meant to discover apps that
        # users may deliberately hide in non-standard locations.  Source 3
        # therefore scans every user-writable directory — NOT just
        # /Applications.  TCC-protected directories (Desktop, Downloads,
        # Documents) are explicitly skipped by `find` to avoid permission
        # prompts, but mdfind and system_profiler cover them anyway.

        collect_candidates() {
          # Source 1: Spotlight index (no TCC required, covers entire indexed FS)
          if /usr/bin/command -v /usr/bin/mdfind >/dev/null 2>&1; then
            timeout_run "$PROFILER_TIMEOUT" /usr/bin/mdfind \
              'kMDItemContentTypeTree == "com.apple.application-bundle"' 2>/dev/null || true
          fi

          # Source 2: LaunchServices DB via system_profiler (no TCC required).
          # Catches apps that Spotlight missed (e.g. Spotlight disabled).
          timeout_run "$PROFILER_TIMEOUT" /usr/sbin/system_profiler SPApplicationsDataType \
            -detailLevel mini 2>/dev/null \
            | /usr/bin/awk -F': ' '/^ *Location: /{print $2}' || true

          # Source 3: Filesystem deep scan.
          # Scan system-level app dirs + every user's home directory.
          # Inside $HOME we skip TCC-protected dirs (Desktop, Downloads,
          # Documents) to avoid permission prompts — mdfind/system_profiler
          # already cover those.

          [ "$WITH_FIND_SCAN" != "1" ] && return 0

          local roots=()
          roots+=("/Applications" "/Applications/Utilities")
          roots+=("/opt" "/usr/local")
          if [ "$INCLUDE_SYSTEM_APPS" = "1" ]; then
            roots+=("/System/Applications" "/System/Applications/Utilities")
          fi
          if [ "$INCLUDE_EXTERNAL_VOLUMES" = "1" ]; then
            for r in /Volumes/*/; do [ -d "$r" ] && roots+=("$r"); done
          fi

          for root in "${roots[@]}"; do
            [ -d "$root" ] || continue
            timeout_run "$FIND_TIMEOUT" /usr/bin/find "$root" -xdev -maxdepth 5 -type d -name '*.app' -prune 2>/dev/null || true
          done

          # Per-user home scan: sweep everything EXCEPT TCC-protected dirs
          # and noisy build/cache dirs.
          local user_home
          for user_home in /Users/*/; do
            [ -d "$user_home" ] || continue
            case "$user_home" in /Users/Shared/|/Users/Guest/) continue ;; esac
            timeout_run "$FIND_TIMEOUT" /usr/bin/find "$user_home" -xdev -maxdepth 6 -type d \
              \( -name Desktop -o -name Downloads -o -name Documents \
                 -o -name Photos -o -name Movies -o -name Music \
                 -o -name .Trash -o -name DerivedData \
                 -o -name node_modules -o -name '.git' \
                 -o -name CoreSimulator \
              \) -prune -o \
              -type d -name '*.app' -print 2>/dev/null || true
          done
        }

        # ── Main: collect → dedup → validate → emit ─────────────────────────

        # ── Homebrew inventory ──────────────────────────────────────────────

        collect_homebrew() {
          local brew_bin=""
          for b in /opt/homebrew/bin/brew /usr/local/bin/brew; do
            [ -x "$b" ] && { brew_bin="$b"; break; }
          done
          [ -n "$brew_bin" ] || return 0

          local formula cask
          formula=$("$brew_bin" list --formula --versions 2>/dev/null || true)
          cask=$("$brew_bin" list --cask --versions 2>/dev/null || true)

          if [ -n "$formula" ]; then
            while IFS= read -r line; do
              [ -n "$line" ] || continue
              local name version
              name="${line%% *}"
              version="${line#* }"
              csv_row "homebrew/formula/$name" "" "$version" "" "" "HF" ""
            done <<< "$formula"
          fi

          if [ -n "$cask" ]; then
            while IFS= read -r line; do
              [ -n "$line" ] || continue
              local name version
              name="${line%% *}"
              version="${line#* }"
              csv_row "homebrew/cask/$name" "" "$version" "" "" "HC" ""
            done <<< "$cask"
          fi
        }

        # ── Chrome/Chromium extension inventory ───────────────────────────────

        collect_chrome_extensions() {
          # Browser relative paths under ~/Library/Application Support
          local browser_specs=(
            "Chrome|Google/Chrome"
            "Edge|Microsoft Edge"
            "Brave|BraveSoftware/Brave-Browser"
            "Chromium|Chromium"
            "Vivaldi|Vivaldi"
            "Arc|Arc/User Data"
            "Opera|com.operasoftware.Opera"
          )

          # Iterate every real user home so we discover extensions
          # for all users, not just the invoking account (root under Jamf).
          local user_home
          for user_home in /Users/*/; do
            [ -d "$user_home" ] || continue
            case "$user_home" in /Users/Shared/|/Users/Guest/) continue ;; esac

            local spec browser_name browser_rel browser_dir
            for spec in "${browser_specs[@]}"; do
              browser_name="${spec%%|*}"
              browser_rel="${spec#*|}"
              browser_dir="${user_home}Library/Application Support/${browser_rel}"
              [ -d "$browser_dir" ] || continue

              local profile_dir
              for profile_dir in "$browser_dir"/*/; do
                local _pd="${profile_dir%/}"
                [ -d "$_pd/Extensions" ] || continue
                local ext_dir
                for ext_dir in "$_pd/Extensions"/*/; do
                  [ -d "$ext_dir" ] || continue
                  local ext_id
                  ext_id="${ext_dir%/}" && ext_id="${ext_id##*/}"
                  [ -n "$ext_id" ] || continue

                  # Find latest version's manifest.json
                  local manifest_file="" ver_dir
                  for ver_dir in "$ext_dir"/*/; do
                    [ -f "$ver_dir/manifest.json" ] && manifest_file="$ver_dir/manifest.json"
                  done
                  [ -n "$manifest_file" ] || continue

                  local ext_version
                  ext_version="${manifest_file%/manifest.json}" && ext_version="${ext_version##*/}"
                  csv_row "$ext_dir" "$ext_id" "$ext_version" "" "" "X" ""
                done
              done
            done
          done
        }

        # ── Main: collect → dedup → validate → emit ─────────────────────────

        generate_csv() {
          if [ "$WITH_NICE" = "1" ]; then
            /usr/bin/renice 10 $$ >/dev/null 2>&1 || true
          fi

          # CSV header
          csv_row p b v lu bt s pe

          if [ "$WITH_APP_SCAN" != "1" ]; then
            # Skip .app scanning entirely; only homebrew/extensions if enabled
            if [ "$WITH_HOMEBREW" = "1" ]; then collect_homebrew; fi
            if [ "$WITH_CHROME_EXTENSIONS" = "1" ]; then collect_chrome_extensions; fi
            return 0
          fi

          # Pipeline: collect all candidates → sort -u dedup → process each
          collect_candidates | /usr/bin/sort -u | while IFS= read -r app; do
            [ -n "$app" ] || continue

            local canonical
            canonical="$(canonical_dir "$app")"
            [ -n "$canonical" ] || canonical="$app"

            is_valid_app_bundle "$canonical" || continue
            should_emit_app "$app" "$canonical" || continue

            local plist bundle_id version last_used birth_time source_hint plist_error
            plist="$canonical/Contents/Info.plist"
            plist_error="$(plist_status "$plist")"

            bundle_id="$(plist_get "$plist" CFBundleIdentifier)"
            version="$(plist_get "$plist" CFBundleShortVersionString)"

            # kMDItemLastUsedDate: maintained by LaunchServices, only updated
            # on user-initiated launch — not by Spotlight or filesystem scans
            last_used="$(/usr/bin/mdls -name kMDItemLastUsedDate -raw "$canonical" 2>/dev/null || true)"
            last_used="$(to_epoch "$last_used")"

            birth_time="$(/usr/bin/stat -f '%B' "$canonical" 2>/dev/null || true)"

            source_hint="O"
            case "$app" in
              /Applications/*|/Users/*/Applications/*)
                source_hint="A" ;;
              /Volumes/*) source_hint="V" ;;
            esac

            csv_row "$canonical" "$bundle_id" "$version" "$last_used" "$birth_time" "$source_hint" "$plist_error"
          done

          # Homebrew packages (formula + cask)
          if [ "$WITH_HOMEBREW" = "1" ]; then
            collect_homebrew
          fi

          # Chrome/Chromium browser extensions
          if [ "$WITH_CHROME_EXTENSIONS" = "1" ]; then
            collect_chrome_extensions
          fi
        }

        emit_base64_result() {
          local payload=""
          payload="$(generate_csv | /usr/bin/base64 | /usr/bin/tr -d '\n')"
          printf '<result>%s</result>\n' "$payload"
        }

        main() {
          if [ "$QUIET" = "1" ]; then
            exec 2>/dev/null
          fi
          emit_base64_result
        }

        main "$@"
