        #!/bin/bash
        set -u
        set -o pipefail

        # macOS App Inventory
        # Maintained directly — no longer generated by app_inventory.py.
        # READ-ONLY: no file writes, no temp files, no cleanup.
        # All output to stdout. Deploy via MDM; framework captures output.

        INCLUDE_SYSTEM_APPS="${INCLUDE_SYSTEM_APPS:-0}"
        INCLUDE_EXTERNAL_VOLUMES="${INCLUDE_EXTERNAL_VOLUMES:-0}"
        WITH_SIGNATURE="${WITH_SIGNATURE:-0}"
        WITH_PKG_RECEIPT="${WITH_PKG_RECEIPT:-0}"
        WITH_HOMEBREW="${WITH_HOMEBREW:-0}"
        WITH_CHROME_EXTENSIONS="${WITH_CHROME_EXTENSIONS:-0}"
        WITH_APP_SCAN="${WITH_APP_SCAN:-1}"
        WITH_FIND_SCAN="${WITH_FIND_SCAN:-1}"
        FIND_TIMEOUT="${FIND_TIMEOUT:-30}"
        PROFILER_TIMEOUT="${PROFILER_TIMEOUT:-30}"
        WITH_NICE="${WITH_NICE:-0}"

        # ── Command helpers ───────────────────────────────────────────────────

        timeout_run() {
          local seconds="$1"
          shift

          if [ -x /opt/homebrew/bin/gtimeout ]; then
            /opt/homebrew/bin/gtimeout "$seconds" "$@"
          elif [ -x /usr/local/bin/gtimeout ]; then
            /usr/local/bin/gtimeout "$seconds" "$@"
          elif command -v timeout >/dev/null 2>&1; then
            timeout "$seconds" "$@"
          else
            "$@"
          fi
        }

        # ── CSV helpers ──────────────────────────────────────────────────────

        csv_escape() {
          local s="${1:-}"
          s=${s//\"/\"\"}
          printf '\"%s\"' "$s"
        }

        csv_row() {
          local first=1 field
          for field in "$@"; do
            if [ "$first" -eq 1 ]; then first=0; else printf ','; fi
            csv_escape "$field"
          done
          printf '\n'
        }

        # ── Plist / path helpers ─────────────────────────────────────────────

        plist_get() {
          /usr/libexec/PlistBuddy -c "Print :$2" "$1" 2>/dev/null || true
        }

        canonical_dir() {
          ( cd "$1" 2>/dev/null && /bin/pwd -P ) || true
        }

        # ── Bundle validation ────────────────────────────────────────────────

        is_valid_app_bundle() {
          # Returns 0 (valid) for any .app directory that has Info.plist.
          # We intentionally do NOT require CFBundleExecutable to exist
          # or be executable — some apps use non-standard structures
          # (script wrappers, symlinked executables, etc.) and we'd rather
          # over-report than silently miss a risk app.
          local app="$1"
          [ -d "$app" ] || return 1
          case "$app" in *.app) ;; *) return 1 ;; esac

          # Info.plist is the minimum bar — without it, it's not an app bundle
          [ -f "$app/Contents/Info.plist" ] || return 1
          return 0
        }

        is_nested_app() {
          case "$1" in
            *.app/Contents/*) return 0 ;;
            *.app/Versions/*) return 0 ;;
            *) return 1 ;;
          esac
        }

        is_noisy_path() {
          local app="$1"
          # Resolve APFS firmlink prefix so /System/Volumes/Data/Users/...
          # is evaluated as /Users/... instead of being blanket-dropped.
          case "$app" in /System/Volumes/Data/*) app="/${app#/System/Volumes/Data/}" ;; esac

          case "$app" in
            # True system internals — not user-installed apps
            /System/Volumes/*) return 0 ;;
            /private/var/*|/private/tmp/*|/tmp/*) return 0 ;;
            */.Trash/*) return 0 ;;
          esac
          if [ "$INCLUDE_EXTERNAL_VOLUMES" != "1" ]; then
            case "$app" in /Volumes/*) return 0 ;; esac
          fi
          return 1
        }

        should_emit_app() {
          local app="$1" plist bundle_id
          is_nested_app "$app" && return 1
          is_noisy_path "$app" && return 1

          if [ "$INCLUDE_SYSTEM_APPS" != "1" ]; then
            case "$app" in
              /System/Applications/*|/System/Library/*) return 1 ;;
            esac
            plist="$app/Contents/Info.plist"
            bundle_id="$(plist_get "$plist" CFBundleIdentifier)"
            case "$bundle_id" in com.apple.*) return 1 ;; esac
          fi
          return 0
        }

        # ── Candidate collection (stdout only, no temp files) ────────────────
        #
        # ADVERSARIAL DESIGN: This script is meant to discover apps that
        # users may deliberately hide in non-standard locations.  Source 3
        # therefore scans every user-writable directory — NOT just
        # /Applications.  TCC-protected directories (Desktop, Downloads,
        # Documents) are explicitly skipped by `find` to avoid permission
        # prompts, but mdfind and system_profiler cover them anyway.

        collect_candidates() {
          # Source 1: Spotlight index (no TCC required, covers entire indexed FS)
          if /usr/bin/command -v /usr/bin/mdfind >/dev/null 2>&1; then
            timeout_run "$PROFILER_TIMEOUT" /usr/bin/mdfind \
              'kMDItemContentTypeTree == "com.apple.application-bundle"' 2>/dev/null || true
          fi

          # Source 2: LaunchServices DB via system_profiler (no TCC required).
          # Catches apps that Spotlight missed (e.g. Spotlight disabled).
          timeout_run "$PROFILER_TIMEOUT" /usr/sbin/system_profiler SPApplicationsDataType \
            -detailLevel mini 2>/dev/null \
            | /usr/bin/awk -F': ' '/^ *Location: /{print $2}' || true

          # Source 3: Filesystem deep scan.
          # Scan system-level app dirs + every user's home directory.
          # Inside $HOME we skip TCC-protected dirs (Desktop, Downloads,
          # Documents) to avoid permission prompts — mdfind/system_profiler
          # already cover those.

          [ "$WITH_FIND_SCAN" != "1" ] && return 0

          local roots=()
          roots+=("/Applications" "/Applications/Utilities")
          roots+=("/opt" "/usr/local")
          if [ "$INCLUDE_SYSTEM_APPS" = "1" ]; then
            roots+=("/System/Applications" "/System/Applications/Utilities")
          fi
          if [ "$INCLUDE_EXTERNAL_VOLUMES" = "1" ]; then
            for r in /Volumes/*/; do [ -d "$r" ] && roots+=("$r"); done
          fi

          for root in "${roots[@]}"; do
            [ -d "$root" ] || continue
            timeout_run "$FIND_TIMEOUT" /usr/bin/find "$root" -xdev -maxdepth 5 -type d -name '*.app' -prune 2>/dev/null || true
          done

          # Per-user home scan: sweep everything EXCEPT TCC-protected dirs
          # and noisy build/cache dirs.
          local user_home
          for user_home in /Users/*/; do
            [ -d "$user_home" ] || continue
            case "$user_home" in /Users/Shared/|/Users/Guest/) continue ;; esac
            timeout_run "$FIND_TIMEOUT" /usr/bin/find "$user_home" -xdev -maxdepth 6 -type d \
              \( -name Desktop -o -name Downloads -o -name Documents \
                 -o -name Photos -o -name Movies -o -name Music \
                 -o -name .Trash -o -name DerivedData \
                 -o -name node_modules -o -name '.git' \
                 -o -name CoreSimulator \
              \) -prune -o \
              -type d -name '*.app' -print 2>/dev/null || true
          done
        }

        # ── Optional enrichment ──────────────────────────────────────────────

        signature_summary() {
          local app="$1" out signed team_id authority gatekeeper
          signed="no"; team_id=""; authority=""; gatekeeper=""

          out="$(/usr/bin/codesign -dv --verbose=4 "$app" 2>&1 || true)"
          if printf '%s\n' "$out" | /usr/bin/grep -q '^TeamIdentifier='; then
            signed="yes"
            team_id="$(printf '%s\n' "$out" | /usr/bin/awk -F= '/^TeamIdentifier=/{print $2; exit}')"
            authority="$(printf '%s\n' "$out" | /usr/bin/awk -F= '/^Authority=/{print $2; exit}')"
          fi
          gatekeeper="$(/usr/sbin/spctl -a -vv --type execute "$app" 2>&1 | /usr/bin/tail -n 1 || true)"
          printf '%s|%s|%s|%s' "$signed" "$team_id" "$authority" "$gatekeeper"
        }

        pkg_receipt_summary() {
          local app="$1" probe_path file_info pkgid install_info install_time
          probe_path="$app/Contents/Info.plist"
          [ -f "$probe_path" ] || probe_path="$app"

          file_info="$(/usr/sbin/pkgutil --file-info "$probe_path" 2>/dev/null || true)"
          pkgid="$(printf '%s\n' "$file_info" | /usr/bin/awk -F': ' '/pkgid:/{print $2; exit}')"
          [ -n "$pkgid" ] || { printf '|'; return 0; }

          install_info="$(/usr/sbin/pkgutil --pkg-info "$pkgid" 2>/dev/null || true)"
          install_time="$(printf '%s\n' "$install_info" | /usr/bin/awk -F': ' '/install-time:/{print $2; exit}')"
          printf '%s|%s' "$pkgid" "$install_time"
        }

        # ── Main: collect → dedup → validate → emit ─────────────────────────

        # ── Homebrew inventory ──────────────────────────────────────────────

        collect_homebrew() {
          local brew_bin=""
          for b in /opt/homebrew/bin/brew /usr/local/bin/brew; do
            [ -x "$b" ] && { brew_bin="$b"; break; }
          done
          [ -n "$brew_bin" ] || return 0

          local formula cask
          formula=$("$brew_bin" list --formula --versions 2>/dev/null || true)
          cask=$("$brew_bin" list --cask --versions 2>/dev/null || true)

          if [ -n "$formula" ]; then
            while IFS= read -r line; do
              [ -n "$line" ] || continue
              local name version
              name="${line%% *}"
              version="${line#* }"
              csv_row \
                "homebrew/formula/$name" "$name" "" "$version" "" \
                "" "" "" \
                "" "" \
                "" "" "homebrew_formula"
            done <<< "$formula"
          fi

          if [ -n "$cask" ]; then
            while IFS= read -r line; do
              [ -n "$line" ] || continue
              local name version
              name="${line%% *}"
              version="${line#* }"
              csv_row \
                "homebrew/cask/$name" "$name" "" "$version" "" \
                "" "" "" \
                "" "" \
                "" "" "homebrew_cask"
            done <<< "$cask"
          fi
        }

        # ── Chrome/Chromium extension inventory ───────────────────────────────

        collect_chrome_extensions() {
          local browser_name browser_dir
          while IFS=$'\t' read -r browser_name browser_dir; do
            [ -d "$browser_dir" ] || continue
            local profile_dir
            for profile_dir in "$browser_dir"/*/; do
              local _pd="${profile_dir%/}"
              [ -d "$_pd/Extensions" ] || continue
              local ext_dir
              for ext_dir in "$_pd/Extensions"/*/; do
                [ -d "$ext_dir" ] || continue
                local ext_id
                ext_id="${ext_dir%/}" && ext_id="${ext_id##*/}"
                [ -n "$ext_id" ] || continue

                # Find latest version's manifest.json
                local manifest_file="" ver_dir
                for ver_dir in "$ext_dir"/*/; do
                  [ -f "$ver_dir/manifest.json" ] && manifest_file="$ver_dir/manifest.json"
                done
                [ -n "$manifest_file" ] || continue

                local ext_version ext_name
                ext_version="${manifest_file%/manifest.json}" && ext_version="${ext_version##*/}"

                # Extract name via python3 (handles __MSG_ i18n placeholders)
                ext_name=$(/usr/bin/python3 -c "
import json, sys, os
try:
    mf = sys.argv[1]
    with open(mf) as f: m = json.load(f)
    name = m.get('name', '')
    if name.startswith('__MSG_') and name.endswith('__'):
        key = name[6:-2]
        ld = os.path.join(os.path.dirname(mf), '_locales')
        for lang in ['en', 'en_US', 'en_GB']:
            p = os.path.join(ld, lang, 'messages.json')
            if os.path.isfile(p):
                with open(p) as lf: msgs = json.load(lf)
                for k, v in msgs.items():
                    if k.lower() == key.lower():
                        name = v.get('message', name); break
                break
    print(name)
except Exception: pass
" "$manifest_file" 2>/dev/null || true)
                [ -n "$ext_name" ] || ext_name="$ext_id"

                local profile_name
                profile_name="${profile_dir%/}" && profile_name="${profile_name##*/}"

                csv_row \
                  "$ext_dir" "$ext_name" "$ext_id" "$ext_version" "" \
                  "" "" "" \
                  "" "" \
                  "" "" "chrome_ext/$browser_name/$profile_name"
              done
            done
          done <<EOF
Chrome	$HOME/Library/Application Support/Google/Chrome
Edge	$HOME/Library/Application Support/Microsoft Edge
Brave	$HOME/Library/Application Support/BraveSoftware/Brave-Browser
Chromium	$HOME/Library/Application Support/Chromium
Vivaldi	$HOME/Library/Application Support/Vivaldi
Arc	$HOME/Library/Application Support/Arc/User Data
Opera	$HOME/Library/Application Support/com.operasoftware.Opera
EOF
        }

        # ── Main: collect → dedup → validate → emit ─────────────────────────

        generate_csv() {
          if [ "$WITH_NICE" = "1" ]; then
            /usr/bin/renice 10 $$ >/dev/null 2>&1 || true
          fi

          # CSV header
          csv_row \
            path display_name bundle_id version build \
            team_id signed gatekeeper \
            last_used_date bundle_birth_time \
            receipt_pkgid receipt_install_time source_hint

          if [ "$WITH_APP_SCAN" != "1" ]; then
            # Skip .app scanning entirely; only homebrew/extensions if enabled
            if [ "$WITH_HOMEBREW" = "1" ]; then collect_homebrew; fi
            if [ "$WITH_CHROME_EXTENSIONS" = "1" ]; then collect_chrome_extensions; fi
            return 0
          fi

          # Pipeline: collect all candidates → sort -u dedup → process each
          collect_candidates | /usr/bin/sort -u | while IFS= read -r app; do
            [ -n "$app" ] || continue

            local canonical
            canonical="$(canonical_dir "$app")"
            [ -n "$canonical" ] || canonical="$app"

            is_valid_app_bundle "$canonical" || continue
            should_emit_app "$canonical" || continue

            local plist bundle_id bundle_name display_name version build
            local last_used birth_time source_hint
            plist="$canonical/Contents/Info.plist"

            bundle_id="$(plist_get "$plist" CFBundleIdentifier)"
            bundle_name="$(plist_get "$plist" CFBundleName)"
            display_name="$(plist_get "$plist" CFBundleDisplayName)"
            version="$(plist_get "$plist" CFBundleShortVersionString)"
            build="$(plist_get "$plist" CFBundleVersion)"

            if [ -z "$display_name" ]; then
              if [ -n "$bundle_name" ]; then
                display_name="$bundle_name"
              else
                display_name="$(/usr/bin/basename "$canonical" .app)"
              fi
            fi

            # kMDItemLastUsedDate: maintained by LaunchServices, only updated
            # on user-initiated launch — not by Spotlight or filesystem scans
            last_used="$(/usr/bin/mdls -name kMDItemLastUsedDate -raw "$canonical" 2>/dev/null || true)"
            case "$last_used" in "(null)"|*"could not find"*) last_used="" ;; esac

            birth_time="$(/usr/bin/stat -f '%SB' -t '%Y-%m-%d %H:%M:%S' "$canonical" 2>/dev/null || true)"

            source_hint="off_standard_path"
            case "$canonical" in
              /Applications/*|/Users/*/Applications/*|"$HOME"/Applications/*)
                source_hint="standard_app_dir" ;;
              /Volumes/*) source_hint="external_volume" ;;
            esac

            local signed="" team_id="" authority="" gatekeeper=""
            if [ "$WITH_SIGNATURE" = "1" ]; then
              local sig
              sig="$(signature_summary "$canonical")"
              signed="$(printf '%s' "$sig" | /usr/bin/awk -F'|' '{print $1}')"
              team_id="$(printf '%s' "$sig" | /usr/bin/awk -F'|' '{print $2}')"
              authority="$(printf '%s' "$sig" | /usr/bin/awk -F'|' '{print $3}')"
              gatekeeper="$(printf '%s' "$sig" | /usr/bin/awk -F'|' '{print $4}')"
            fi

            local pkgid="" install_time=""
            if [ "$WITH_PKG_RECEIPT" = "1" ]; then
              local pkg
              pkg="$(pkg_receipt_summary "$canonical")"
              pkgid="$(printf '%s' "$pkg" | /usr/bin/awk -F'|' '{print $1}')"
              install_time="$(printf '%s' "$pkg" | /usr/bin/awk -F'|' '{print $2}')"
            fi

            csv_row \
              "$canonical" "$display_name" "$bundle_id" "$version" "$build" \
              "$team_id" "$signed" "$gatekeeper" \
              "$last_used" "$birth_time" \
              "$pkgid" "$install_time" "$source_hint"
          done

          # Homebrew packages (formula + cask)
          if [ "$WITH_HOMEBREW" = "1" ]; then
            collect_homebrew
          fi

          # Chrome/Chromium browser extensions
          if [ "$WITH_CHROME_EXTENSIONS" = "1" ]; then
            collect_chrome_extensions
          fi
        }

        emit_base64_result() {
          local payload=""
          payload="$(generate_csv | /usr/bin/base64 | /usr/bin/tr -d '\n')"
          printf '<result>%s</result>\n' "$payload"
        }

        main() {
          emit_base64_result
        }

        main "$@"
