#!/usr/bin/env python3
"""Generate ES|QL network detection rules from app YAML files.

Only includes apps whose network IOC group meets the --min-status threshold.
Optionally filters to a specific app category.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date

from app_control.catalog import filter_apps_with_ioc_group


def load_apps(min_status: str, category: str | None = None) -> list[dict]:
    return filter_apps_with_ioc_group("network", min_status=min_status, category=category)


def escape_esql(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_esql(apps: list[dict], min_status: str, category: str | None = None) -> str:
    lines: list[str] = []
    lines.append(f"// Auto-generated by esql_rules.py on {date.today().isoformat()}")
    lines.append(f"// Minimum IOC status: {min_status}")
    if category:
        lines.append(f"// Category filter: {category}")
    lines.append(f"// Apps included: {len(apps)}")
    lines.append("")
    lines.append("// --- Network detection: hostname + keyword matching ---")
    lines.append("")
    lines.append('| EVAL domain_lower = TO_LOWER(COALESCE(dns.question.name, tls.client.server_name, url.domain, ""))')
    lines.append("")

    case_clauses: list[str] = []
    for app in apps:
        app_id = app["id"]
        app_name = app["name"]
        net = app["iocs"]["network"]
        patterns = net.get("hostname_patterns", [])
        keywords = net.get("keyword_patterns", [])

        conditions: list[str] = []

        exact = [pattern["pattern"] for pattern in patterns if pattern["match"] == "exact"]
        for exact_match in exact:
            conditions.append(f'domain_lower == "{escape_esql(exact_match)}"')

        suffix = [pattern["pattern"] for pattern in patterns if pattern["match"] == "suffix"]
        for suffix_match in suffix:
            conditions.append(
                f'(domain_lower == "{escape_esql(suffix_match)}" OR domain_lower LIKE "*.{escape_esql(suffix_match)}")'
            )

        for keyword_pattern in keywords:
            pattern = keyword_pattern["pattern"]
            if keyword_pattern["match"] == "substring":
                conditions.append(f'domain_lower LIKE "*{escape_esql(pattern)}*"')
            elif keyword_pattern["match"] == "regex":
                conditions.append(f'domain_lower RLIKE "{escape_esql(pattern)}"')

        if conditions:
            joined = "\n    OR ".join(conditions)
            case_clauses.append(f'  // {app_name} ({app_id})\n  {joined}, "{escape_esql(app_id)}"')

    lines.append("| EVAL ai_tool = CASE(")
    lines.append(",\n".join(case_clauses))
    lines.append(")")
    lines.append("")
    lines.append("| WHERE ai_tool IS NOT NULL")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate ES|QL network detection rules")
    parser.add_argument(
        "--min-status",
        default="validated",
        choices=["draft", "reviewed", "validated"],
        help="Minimum IOC status to include (default: validated)",
    )
    parser.add_argument("--category", default=None, help="Only include apps in the given category")
    args = parser.parse_args()

    apps = load_apps(args.min_status, args.category)
    if not apps:
        suffix = f" in category '{args.category}'" if args.category else ""
        print(f"// No apps meet min-status '{args.min_status}'{suffix}. No rules generated.", file=sys.stderr)
        sys.exit(0)

    output = generate_esql(apps, args.min_status, args.category)
    sys.stdout.write(output)


if __name__ == "__main__":
    main()
