#!/usr/bin/env python3
"""Generate Jamf/MDM host scanning scripts from app YAML files.

The generated script has two sections:
1. Targeted detection: per-app checks for known IOCs (paths, bundle IDs,
   process names, Chrome extension IDs, repo/project searches).
2. Inventory discovery: enumerates uncataloged apps and CLI tools via
   system_profiler, mdfind, and package manager filesystem scans.

system_profiler SPApplicationsDataType -json provides _name, path, version,
obtained_from, and signed_by. It does NOT provide bundle IDs or team IDs —
those are looked up from Info.plist (defaults read) and codesign output.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date

from app_control.catalog import filter_apps_with_ioc_group

GENERIC_DIR_NAMES = {
    "app",
    "api",
    "bin",
    "build",
    "client",
    "config",
    "configs",
    "data",
    "developer",
    "dist",
    "docs",
    "frontend",
    "lib",
    "log",
    "logs",
    "output",
    "server",
    "src",
    "web",
}

_USER_BIN_PREFIXES = (".local/bin/", ".cargo/bin/", "go/bin/", ".go/bin/")
_SYSTEM_BIN_DIRS = ("/opt/homebrew/bin", "/usr/local/bin")
_NPM_GLOBAL_DIRS = ("/opt/homebrew/lib/node_modules", "/usr/local/lib/node_modules")


def load_apps(min_status: str, category: str | None = None) -> list[dict]:
    return filter_apps_with_ioc_group("host", min_status=min_status, category=category)


def shell_escape(value: str) -> str:
    return value.replace("'", "'\\''")


def classify_path(path: str) -> tuple[str, str]:
    """Classify an IOC path into a scan strategy."""
    if (
        path.startswith("~/")
        or path.startswith("$HOME/")
        or path.startswith("${HOME}/")
    ):
        normalized = (
            path.replace("~/", "").replace("$HOME/", "").replace("${HOME}/", "")
        )
        return "user", normalized

    if path.startswith("/"):
        return "system", path

    if path.startswith("*/"):
        inner = path[2:]
        first_component = inner.split("/")[0]
        if (
            first_component
            and first_component.lower() not in GENERIC_DIR_NAMES
            and not first_component.startswith(".")
        ):
            return "repo", inner
        return "project", inner

    if path.startswith("./"):
        return "project", path[2:]

    if path.startswith("*"):
        return "project", path

    return "project", path


def emit_shell_array(
    lines: list[str], var_name: str, values: list[str], indent: str = ""
) -> None:
    lines.append(f"{indent}{var_name}=(")
    for value in values:
        lines.append(f'{indent}    "{shell_escape(value)}"')
    lines.append(f"{indent})")


def generate_scan_script(
    apps: list[dict],
    min_status: str,
    category: str | None = None,
    *,
    output_mode: str = "report",
) -> str:
    lines: list[str] = []

    lines.append("#!/bin/bash")
    lines.append(f"# Auto-generated by jamf_scan.py on {date.today().isoformat()}")
    lines.append(f"# Minimum IOC status: {min_status}")
    if category:
        lines.append(f"# Category filter: {category}")
    lines.append(f"# Apps scanned: {len(apps)}")
    lines.append(f"# Output mode: {output_mode}")
    lines.append("")
    lines.append("set -euo pipefail")
    lines.append("")
    lines.append("RESULTS=()")
    lines.append('FOUND_IDS="|"')
    lines.append("")

    lines.extend(
        [
            "app_found() {",
            '    local app_id="$1"',
            '    case "$FOUND_IDS" in',
            '        *"|$app_id|"*) return 0 ;;',
            "        *) return 1 ;;",
            "    esac",
            "}",
            "",
            "mark_found() {",
            '    local app_id="$1"',
            '    FOUND_IDS="${FOUND_IDS}${app_id}|"',
            "}",
            "",
            "get_times() {",
            '    local path="$1"',
            "    local times",
            '    times=$(/usr/bin/stat -f "%SB|%Sa" -t "%Y-%m-%d %H:%M:%S" "$path" 2>/dev/null || true)',
            '    if [ -n "$times" ]; then',
            '        echo "$times"',
            "    else",
            '        echo "UNKNOWN|UNKNOWN"',
            "    fi",
            "}",
            "",
            "record_path_match() {",
            '    local app_id="$1"',
            '    local path="$2"',
            "    local times install_time last_access",
            '    if [ -n "$path" ] && [ "$path" != "UNKNOWN" ] && [ -e "$path" ]; then',
            '        times=$(get_times "$path")',
            "    else",
            '        times="UNKNOWN|UNKNOWN"',
            "    fi",
            "    install_time=${times%%|*}",
            "    last_access=${times#*|}",
            '    RESULTS+=("$app_id|PATH=$path|INSTALL_APPROX=$install_time|LAST_ACCESS=$last_access")',
            '    mark_found "$app_id"',
            "}",
            "",
            "record_bundle_match() {",
            '    local app_id="$1"',
            '    local bundle_id="$2"',
            '    local path="$3"',
            "    local times install_time last_access",
            '    if [ -n "$path" ] && [ "$path" != "UNKNOWN" ] && [ -e "$path" ]; then',
            '        times=$(get_times "$path")',
            "    else",
            '        times="UNKNOWN|UNKNOWN"',
            "    fi",
            "    install_time=${times%%|*}",
            "    last_access=${times#*|}",
            '    RESULTS+=("$app_id|BUNDLE_ID=$bundle_id|PATH=$path|INSTALL_APPROX=$install_time|LAST_ACCESS=$last_access")',
            '    mark_found "$app_id"',
            "}",
            "",
            "record_process_match() {",
            '    local app_id="$1"',
            '    local process_name="$2"',
            '    RESULTS+=("$app_id|PROCESS=$process_name")',
            '    mark_found "$app_id"',
            "}",
            "",
            "record_extension_match() {",
            '    local app_id="$1"',
            '    local ext_id="$2"',
            '    local ext_path="$3"',
            '    RESULTS+=("$app_id|CHROME_EXT=$ext_id|PATH=$ext_path")',
            '    mark_found "$app_id"',
            "}",
            "",
            "check_chrome_extension() {",
            '    local app_id="$1"',
            '    local ext_id="$2"',
            "    local h ext_path",
            '    for h in "${USER_HOMES[@]}"; do',
            '        for profile_dir in "$h/Library/Application Support/Google/Chrome"/*; do',
            '            [ -d "$profile_dir/Extensions/$ext_id" ] || continue',
            '            record_extension_match "$app_id" "$ext_id" "$profile_dir/Extensions/$ext_id"',
            "            return 0",
            "        done",
            "    done",
            "    return 1",
            "}",
            "",
            "check_candidate_pattern() {",
            '    local app_id="$1"',
            '    local candidate="$2"',
            '    local match=""',
            '    if [[ "$candidate" == *"*"* || "$candidate" == *"?"* || "$candidate" == *"["* ]]; then',
            '        match=$(compgen -G "$candidate" 2>/dev/null | head -1 || true)',
            '        if [ -n "$match" ]; then',
            '            record_path_match "$app_id" "$match"',
            "            return 0",
            "        fi",
            '    elif [ -e "$candidate" ]; then',
            '        record_path_match "$app_id" "$candidate"',
            "        return 0",
            "    fi",
            "    return 1",
            "}",
            "",
            "check_app_paths() {",
            '    local app_id="$1"',
            "    shift",
            "    local candidate",
            '    for candidate in "$@"; do',
            '        check_candidate_pattern "$app_id" "$candidate" && return 0',
            "    done",
            "    return 1",
            "}",
            "",
            "check_bundle_id() {",
            '    local app_id="$1"',
            '    local bundle_id="$2"',
            "    local match",
            "    match=$(mdfind \"kMDItemCFBundleIdentifier == '$bundle_id'\" 2>/dev/null | head -1 || true)",
            '    if [ -n "$match" ]; then',
            '        record_bundle_match "$app_id" "$bundle_id" "$match"',
            "        return 0",
            "    fi",
            "    return 1",
            "}",
            "",
            "check_process_name() {",
            '    local app_id="$1"',
            '    local process_name="$2"',
            '    if pgrep -x "$process_name" > /dev/null 2>&1; then',
            '        record_process_match "$app_id" "$process_name"',
            "        return 0",
            "    fi",
            "    return 1",
            "}",
            "",
            "search_dirs() {",
            '    local app_id="$1"',
            '    local rel_path="$2"',
            "    local d",
            '    for d in "${SEARCH_DIRS[@]}"; do',
            '        if [ -e "$d/$rel_path" ]; then',
            '            record_path_match "$app_id" "$d/$rel_path"',
            "            return 0",
            "        fi",
            "    done",
            "    return 1",
            "}",
            "",
            "search_name() {",
            '    local app_id="$1"',
            '    local pattern="$2"',
            '    local type_flag="${3:--d}"',
            "    local d match",
            '    for d in "${SEARCH_DIRS[@]}"; do',
            '        match=$(find "$d" -maxdepth 3 "$type_flag" -name "$pattern" -print -quit 2>/dev/null || true)',
            '        if [ -n "$match" ]; then',
            '            record_path_match "$app_id" "$match"',
            "            return 0",
            "        fi",
            "    done",
            "    return 1",
            "}",
            "",
            "USER_HOMES=()",
            "for h in /Users/*; do",
            '    [ -d "$h" ] || continue',
            '    [ "$h" = "/Users/Shared" ] && continue',
            '    USER_HOMES+=("$h")',
            "done",
            "",
            "SEARCH_DIRS=()",
            'SEARCH_DIR_MARKERS="|"',
            "add_search_dir() {",
            '    local dir="$1"',
            '    [ -d "$dir" ] || return 0',
            '    case "$SEARCH_DIR_MARKERS" in',
            '        *"|$dir|"*) return 0 ;;',
            "    esac",
            '    SEARCH_DIRS+=("$dir")',
            '    SEARCH_DIR_MARKERS="${SEARCH_DIR_MARKERS}${dir}|"',
            "}",
            "",
            'for h in "${USER_HOMES[@]}"; do',
            "    for sub in Documents Desktop Downloads code Code repos projects src git workspace dev Development; do",
            '        add_search_dir "$h/$sub"',
            "    done",
            '    add_search_dir "$h"',
            "done",
            "",
        ]
    )

    for app in apps:
        app_id = app["id"]
        app_name = app["name"]
        host = app["iocs"]["host"]
        var_name = app_id.upper().replace("-", "_").replace(".", "_")
        if var_name[0].isdigit():
            var_name = "APP_" + var_name

        system_paths: list[str] = []
        user_paths: list[str] = []
        repo_paths: list[str] = []
        project_paths: list[str] = []

        for path in host.get("paths", []):
            category_name, value = classify_path(path)
            if category_name == "system":
                system_paths.append(value)
            elif category_name == "user":
                user_paths.append(value)
            elif category_name == "repo":
                repo_paths.append(value)
            else:
                project_paths.append(value)

        system_set = set(system_paths)
        for user_path in user_paths:
            for prefix in _USER_BIN_PREFIXES:
                if user_path.startswith(prefix):
                    binary = user_path[len(prefix) :]
                    for system_dir in _SYSTEM_BIN_DIRS:
                        candidate = f"{system_dir}/{binary}"
                        if candidate not in system_set:
                            system_paths.append(candidate)
                            system_set.add(candidate)
                    break

        lines.append(f"# {'─' * 30}")
        lines.append(f"# {app_name} ({app_id})")
        lines.append(f"# {'─' * 30}")

        if system_paths or user_paths:
            emit_shell_array(lines, f"{var_name}_CANDIDATES", system_paths)
            if user_paths:
                lines.append('for h in "${USER_HOMES[@]}"; do')
                lines.append(f"    {var_name}_CANDIDATES+=(")
                for path in user_paths:
                    lines.append(f'        "$h/{shell_escape(path)}"')
                lines.append("    )")
                lines.append("done")
            lines.append("")

        branches: list[str] = []
        if system_paths or user_paths:
            branches.append(
                f'check_app_paths "{app_id}" "${{{var_name}_CANDIDATES[@]}}"'
            )
        for bundle_id in host.get("bundle_ids", []):
            branches.append(f'check_bundle_id "{app_id}" "{shell_escape(bundle_id)}"')
        for process_name in host.get("process_names", []):
            branches.append(
                f'check_process_name "{app_id}" "{shell_escape(process_name)}"'
            )
        for ext_id in host.get("chrome_extension_ids", []):
            branches.append(
                f'check_chrome_extension "{app_id}" "{shell_escape(ext_id)}"'
            )
        for repo_path in repo_paths:
            branches.append(f'search_dirs "{app_id}" "{shell_escape(repo_path)}"')
        for project_path in project_paths:
            first_segment = project_path.rstrip("/").split("/")[0]
            if first_segment.startswith("*"):
                type_flag = "-d" if project_path.endswith("/") else "-f"
                branches.append(
                    f'search_name "{app_id}" "{shell_escape(first_segment)}" {type_flag}'
                )
            elif "/" not in project_path.rstrip("/"):
                type_flag = "-d" if project_path.endswith("/") else "-f"
                branches.append(
                    f'search_name "{app_id}" "{shell_escape(first_segment)}" {type_flag}'
                )
            else:
                parts = project_path.rstrip("/").split("/")
                distinctive = next(
                    (
                        part
                        for part in parts
                        if part.lower() not in GENERIC_DIR_NAMES and part != "."
                    ),
                    parts[-1],
                )
                type_flag = "-d"
                if distinctive == parts[-1] and not project_path.endswith("/"):
                    type_flag = "-f"
                branches.append(
                    f'search_name "{app_id}" "{shell_escape(distinctive)}" {type_flag}'
                )

        if branches:
            lines.append(f'if ! app_found "{app_id}"; then')
            for index, branch in enumerate(branches):
                prefix = "if" if index == 0 else "elif"
                lines.append(f"    {prefix} {branch}; then")
                lines.append("        :")
            lines.append("    fi")
            lines.append("fi")
        lines.append("")

    # --- Inventory Discovery Section ---
    # Build lookups of all known catalog identifiers for cross-referencing
    # against system_profiler, mdfind, and package manager output.
    all_bundle_ids: set[str] = set()
    all_app_names: set[str] = set()
    all_cli_names: set[str] = set()
    _bin_prefixes = (
        "~/.local/bin/",
        "~/.cargo/bin/",
        "~/go/bin/",
        "~/.go/bin/",
        "/opt/homebrew/bin/",
        "/usr/local/bin/",
    )
    for app in apps:
        host = app.get("iocs", {}).get("host") or {}
        for bid in host.get("bundle_ids", []):
            all_bundle_ids.add(bid)
        # Extract CLI binary names from known bin directories
        for path in host.get("paths", []):
            for prefix in _bin_prefixes:
                if path.startswith(prefix):
                    binary = path[len(prefix) :].rstrip("/")
                    if binary and "*" not in binary:
                        all_cli_names.add(binary)
                    break
            # Extract .app display names from paths for fuzzy matching
            if ".app" in path:
                for segment in path.split("/"):
                    if segment.endswith(".app") or ".app" in segment:
                        clean = (
                            segment.replace("*.app", "")
                            .replace(".app", "")
                            .replace("*", "")
                            .strip()
                        )
                        if clean:
                            all_app_names.add(clean)
        # Also add the app id and name as known identifiers
        all_cli_names.add(app["id"])
        all_cli_names.add(app["id"].replace("_", "-"))
        app_name_lower = app.get("name", "").lower().replace(" ", "-")
        if app_name_lower:
            all_cli_names.add(app_name_lower)

    lines.append("# --- Inventory Discovery ---")
    lines.append("# Use system_profiler, mdfind, and package managers to discover")
    lines.append("# apps and CLI tools not in the catalog")
    lines.append("UNKNOWN_APPS=()")
    lines.append("")

    # Emit the known bundle IDs as a lookup string
    lines.append("# Known catalog bundle IDs for cross-reference")
    known_ids_str = "|".join(sorted(all_bundle_ids))
    lines.append(f'KNOWN_BUNDLE_IDS="|{shell_escape(known_ids_str)}|"')
    lines.append("")

    # Emit known app names as a lookup string
    known_names_str = "|".join(sorted(all_app_names))
    lines.append(f'KNOWN_APP_NAMES="|{shell_escape(known_names_str)}|"')
    lines.append("")

    # Emit known CLI binary/package names as a lookup string
    known_cli_str = "|".join(sorted(all_cli_names))
    lines.append("# Known catalog CLI tool names for package manager cross-reference")
    lines.append(f'KNOWN_CLI_NAMES="|{shell_escape(known_cli_str)}|"')
    lines.append("")

    lines.extend(
        [
            "# Helper: get bundle ID from an .app path using defaults or mdls",
            "get_bundle_id_from_path() {",
            '    local app_path="$1"',
            '    local plist="$app_path/Contents/Info.plist"',
            "    local bid",
            "    # Prefer reading the plist directly (works without Spotlight index)",
            '    if [ -f "$plist" ]; then',
            '        bid=$(/usr/bin/defaults read "$plist" CFBundleIdentifier 2>/dev/null || true)',
            '        if [ -n "$bid" ]; then',
            '            echo "$bid"',
            "            return",
            "        fi",
            "    fi",
            "    # Fallback to Spotlight metadata",
            '    bid=$(mdls -name kMDItemCFBundleIdentifier -raw "$app_path" 2>/dev/null || true)',
            '    if [ -n "$bid" ] && [ "$bid" != "(null)" ]; then',
            '        echo "$bid"',
            "        return",
            "    fi",
            "}",
            "",
            "# Helper: extract team ID from codesign output",
            "get_team_id_from_path() {",
            '    local app_path="$1"',
            "    local line",
            '    line=$(/usr/bin/codesign -dvv "$app_path" 2>&1 | grep "^TeamIdentifier=" || true)',
            '    if [ -n "$line" ]; then',
            '        echo "${line#TeamIdentifier=}"',
            "    fi",
            "}",
            "",
            "# Discover installed applications via system_profiler",
            "# Note: system_profiler -json returns _name, path, version, obtained_from,",
            "# signed_by (array), lastModified, arch_kind. It does NOT return bundle IDs",
            "# or team IDs directly -- those must be looked up separately.",
            "discover_via_system_profiler() {",
            "    local profiler_json",
            "    profiler_json=$(/usr/sbin/system_profiler SPApplicationsDataType -json 2>/dev/null || true)",
            '    if [ -z "$profiler_json" ]; then',
            "        return",
            "    fi",
            "",
            "    # Parse system_profiler JSON using the actual field names:",
            "    # _name, path, version, obtained_from, signed_by (array)",
            "    local parsed",
            '    parsed=$(/usr/bin/python3 -c "',
            "import sys, json, re",
            "data = json.load(sys.stdin)",
            "apps = data.get('SPApplicationsDataType', [])",
            "for app in apps:",
            "    name = app.get('_name', '')",
            "    path = app.get('path', '')",
            "    version = app.get('version', 'UNKNOWN')",
            "    obtained = app.get('obtained_from', 'unknown')",
            "    # Extract team ID from signed_by array (e.g. 'Developer ID Application: Name (TEAMID)')",
            "    team_id = ''",
            "    signed_by = app.get('signed_by', [])",
            "    if signed_by and isinstance(signed_by, list):",
            "        m = re.search(r'\\(([A-Z0-9]{10})\\)', signed_by[0])",
            "        if m:",
            "            team_id = m.group(1)",
            "    if not team_id:",
            "        team_id = 'UNKNOWN'",
            "    print(f'{name}\\t{path}\\t{version}\\t{obtained}\\t{team_id}')",
            '" <<< "$profiler_json" 2>/dev/null || true)',
            "",
            '    if [ -z "$parsed" ]; then',
            "        return",
            "    fi",
            "",
            "    while IFS=$'\\t' read -r sp_name sp_path sp_version sp_obtained sp_team; do",
            '        [ -n "$sp_name" ] || continue',
            "",
            "        # Skip Apple system applications",
            '        case "$sp_obtained" in',
            "            apple) continue ;;",
            "        esac",
            '        case "$sp_path" in',
            "            /System/*|/Library/Apple/*) continue ;;",
            "        esac",
            "",
            "        # Look up the bundle ID from the app path (system_profiler doesn't provide it)",
            "        local sp_bundle",
            '        sp_bundle=$(get_bundle_id_from_path "$sp_path" 2>/dev/null || true)',
            '        if [ -z "$sp_bundle" ]; then',
            '            sp_bundle="UNKNOWN"',
            "        fi",
            "",
            "        # Check if bundle ID is in our known catalog",
            "        local known=0",
            '        if [ "$sp_bundle" != "UNKNOWN" ]; then',
            '            case "$KNOWN_BUNDLE_IDS" in',
            '                *"|$sp_bundle|"*) known=1 ;;',
            "            esac",
            "        fi",
            "",
            "        # Check if app name matches a known catalog entry",
            '        if [ "$known" -eq 0 ] && [ -n "$sp_name" ]; then',
            '            case "$KNOWN_APP_NAMES" in',
            '                *"|$sp_name|"*) known=1 ;;',
            "            esac",
            "        fi",
            "",
            '        if [ "$known" -eq 0 ]; then',
            '            UNKNOWN_APPS+=("UNKNOWN_APP|NAME=$sp_name|BUNDLE_ID=$sp_bundle|PATH=$sp_path|VERSION=$sp_version|TEAM_ID=$sp_team|SOURCE=$sp_obtained")',
            "        fi",
            '    done <<< "$parsed"',
            "}",
            "",
            "# Discover .app bundles via mdfind (Spotlight)",
            "discover_via_mdfind() {",
            "    local mdfind_results",
            "    mdfind_results=$(mdfind \"kMDItemContentTypeTree == 'com.apple.application-bundle'\" 2>/dev/null || true)",
            '    if [ -z "$mdfind_results" ]; then',
            "        return",
            "    fi",
            "",
            "    while IFS= read -r app_path; do",
            '        [ -n "$app_path" ] || continue',
            "",
            "        # Skip system paths",
            '        case "$app_path" in',
            "            /System/*|/Library/Apple/*|/usr/*) continue ;;",
            "        esac",
            "",
            "        # Extract the .app name from the path",
            "        local app_name",
            '        app_name=$(/usr/bin/basename "$app_path" .app 2>/dev/null || true)',
            '        [ -n "$app_name" ] || continue',
            "",
            "        # Check if already found by system_profiler or known scan",
            "        local already_found=0",
            "        local entry",
            '        for entry in "${UNKNOWN_APPS[@]}" "${RESULTS[@]}"; do',
            '            case "$entry" in',
            '                *"$app_path"*) already_found=1; break ;;',
            "            esac",
            "        done",
            '        [ "$already_found" -eq 1 ] && continue',
            "",
            "        # Check against known app names",
            '        case "$KNOWN_APP_NAMES" in',
            '            *"|$app_name|"*) continue ;;',
            "        esac",
            "",
            "        # Get bundle ID from the .app plist or Spotlight metadata",
            "        local bundle_id",
            '        bundle_id=$(get_bundle_id_from_path "$app_path" 2>/dev/null || true)',
            '        if [ -z "$bundle_id" ]; then',
            '            bundle_id="UNKNOWN"',
            "        fi",
            "",
            "        # Check if bundle ID is known",
            '        if [ "$bundle_id" != "UNKNOWN" ]; then',
            '            case "$KNOWN_BUNDLE_IDS" in',
            '                *"|$bundle_id|"*) continue ;;',
            "            esac",
            "        fi",
            "",
            '        UNKNOWN_APPS+=("UNKNOWN_APP|NAME=$app_name|BUNDLE_ID=$bundle_id|PATH=$app_path|SOURCE=mdfind")',
            '    done <<< "$mdfind_results"',
            "}",
            "",
            "# Discover CLI tools installed via package managers.",
            "# These use non-native binaries (brew, pip, npm, etc.) that may not exist.",
            "# In Jamf EA mode these are skipped; in report mode they provide useful inventory.",
            "",
            "# Discover Homebrew-installed packages",
            "discover_via_brew() {",
            '    local brew_cmd=""',
            "    if [ -x /opt/homebrew/bin/brew ]; then",
            "        brew_cmd=/opt/homebrew/bin/brew",
            "    elif [ -x /usr/local/bin/brew ]; then",
            "        brew_cmd=/usr/local/bin/brew",
            "    else",
            "        return",
            "    fi",
            "    local brew_list",
            '    brew_list=$("$brew_cmd" list --formula -1 2>/dev/null || true)',
            '    if [ -n "$brew_list" ]; then',
            "        while IFS= read -r formula; do",
            '            [ -n "$formula" ] || continue',
            '            case "$KNOWN_CLI_NAMES" in *"|$formula|"*) continue ;; esac',
            '            case "$KNOWN_APP_NAMES" in *"|$formula|"*) continue ;; esac',
            '            UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$formula|SOURCE=homebrew")',
            '        done <<< "$brew_list"',
            "    fi",
            "    local cask_list",
            '    cask_list=$("$brew_cmd" list --cask -1 2>/dev/null || true)',
            '    if [ -n "$cask_list" ]; then',
            "        while IFS= read -r cask; do",
            '            [ -n "$cask" ] || continue',
            '            case "$KNOWN_CLI_NAMES" in *"|$cask|"*) continue ;; esac',
            '            case "$KNOWN_APP_NAMES" in *"|$cask|"*) continue ;; esac',
            '            UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$cask|SOURCE=homebrew_cask")',
            '        done <<< "$cask_list"',
            "    fi",
            "}",
            "",
            "# Discover Cargo-installed crates (reads JSON manifest, no cargo binary needed)",
            "discover_via_cargo() {",
            "    local h",
            '    for h in "${USER_HOMES[@]}"; do',
            '        local cargo_file="$h/.cargo/.crates2.json"',
            '        [ -f "$cargo_file" ] || continue',
            "        local crates",
            '        crates=$(/usr/bin/python3 -c "',
            "import sys, json",
            "data = json.load(open(sys.argv[1]))",
            "for key in data.get('installs', {}):",
            "    print(key.split(' ')[0])",
            '" "$cargo_file" 2>/dev/null || true)',
            '        [ -n "$crates" ] || continue',
            "        while IFS= read -r crate; do",
            '            [ -n "$crate" ] || continue',
            '            case "$KNOWN_CLI_NAMES" in *"|$crate|"*) continue ;; esac',
            '            UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$crate|SOURCE=cargo|USER=$h")',
            '        done <<< "$crates"',
            "    done",
            "}",
            "",
            "# Discover Go-installed binaries (scans filesystem, no go binary needed)",
            "discover_via_go() {",
            "    local h",
            '    for h in "${USER_HOMES[@]}"; do',
            '        for gobin in "$h/go/bin" "$h/.go/bin"; do',
            '            [ -d "$gobin" ] || continue',
            "            local binary",
            '            for binary in "$gobin"/*; do',
            '                [ -x "$binary" ] || continue',
            "                local bin_name",
            '                bin_name=$(/usr/bin/basename "$binary")',
            '                case "$KNOWN_CLI_NAMES" in *"|$bin_name|"*) continue ;; esac',
            '                UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$bin_name|SOURCE=go|PATH=$binary|USER=$h")',
            "            done",
            "        done",
            "    done",
            "}",
            "",
            "# Discover globally installed npm packages (checks known paths, no npm binary needed)",
            "discover_via_npm() {",
            "    local npm_dir",
            "    for npm_dir in /opt/homebrew/lib/node_modules /usr/local/lib/node_modules; do",
            '        [ -d "$npm_dir" ] || continue',
            "        local pkg_dir",
            '        for pkg_dir in "$npm_dir"/*/; do',
            '            [ -d "$pkg_dir" ] || continue',
            "            local pkg_name",
            '            pkg_name=$(/usr/bin/basename "$pkg_dir")',
            '            [ -n "$pkg_name" ] || continue',
            '            case "$KNOWN_CLI_NAMES" in *"|$pkg_name|"*) continue ;; esac',
            '            UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$pkg_name|SOURCE=npm|PATH=$pkg_dir")',
            "        done",
            "    done",
            "    # Also check per-user global npm installs",
            "    local h",
            '    for h in "${USER_HOMES[@]}"; do',
            '        local user_npm_dir="$h/.npm-global/lib/node_modules"',
            '        [ -d "$user_npm_dir" ] || continue',
            '        for pkg_dir in "$user_npm_dir"/*/; do',
            '            [ -d "$pkg_dir" ] || continue',
            "            local pkg_name",
            '            pkg_name=$(/usr/bin/basename "$pkg_dir")',
            '            case "$KNOWN_CLI_NAMES" in *"|$pkg_name|"*) continue ;; esac',
            '            UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$pkg_name|SOURCE=npm|PATH=$pkg_dir|USER=$h")',
            "        done",
            "    done",
            "}",
            "",
            "# Discover pip/pipx-installed tools (checks filesystem, no pip binary needed)",
            "discover_via_pip() {",
            "    local h",
            '    for h in "${USER_HOMES[@]}"; do',
            "        # Check pipx manifests (structured data, no command needed)",
            '        local pipx_dir="$h/.local/pipx/venvs"',
            '        if [ -d "$pipx_dir" ]; then',
            '            for venv in "$pipx_dir"/*/; do',
            '                [ -d "$venv" ] || continue',
            "                local pkg_name",
            '                pkg_name=$(/usr/bin/basename "$venv")',
            '                case "$KNOWN_CLI_NAMES" in *"|$pkg_name|"*) continue ;; esac',
            '                UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$pkg_name|SOURCE=pipx|USER=$h")',
            "            done",
            "        fi",
            "        # Check user-local bin for non-system executables",
            '        local local_bin="$h/.local/bin"',
            '        if [ -d "$local_bin" ]; then',
            '            for binary in "$local_bin"/*; do',
            '                [ -x "$binary" ] || continue',
            "                local bin_name",
            '                bin_name=$(/usr/bin/basename "$binary")',
            '                case "$KNOWN_CLI_NAMES" in *"|$bin_name|"*) continue ;; esac',
            '                UNKNOWN_APPS+=("UNKNOWN_CLI|NAME=$bin_name|SOURCE=pip_local|PATH=$binary|USER=$h")',
            "            done",
            "        fi",
            "    done",
            "}",
            "",
            "# Run native macOS discovery (always runs)",
            "discover_via_system_profiler",
            "discover_via_mdfind",
            "",
            "# Run package manager filesystem scans",
            "# These only read the filesystem and use native /usr/bin/python3 for JSON parsing.",
            "# They do NOT invoke non-native package manager binaries like pip or npm.",
            "discover_via_cargo",
            "discover_via_go",
            "discover_via_npm",
            "discover_via_pip",
            "",
        ]
    )

    # In report mode, also run brew discovery (uses non-native binary).
    # In jamf_ea mode, skip it -- Jamf best practices require native binaries only.
    if output_mode == "report":
        lines.extend(
            [
                "# Homebrew discovery (report mode only -- uses non-native brew binary)",
                "discover_via_brew",
                "",
            ]
        )

    lines.append("# --- Report ---")
    if output_mode == "jamf_ea":
        lines.extend(
            [
                "COMBINED=()",
                "if [ ${#RESULTS[@]} -gt 0 ]; then",
                '    COMBINED+=("${RESULTS[@]}")',
                "fi",
                "if [ ${#UNKNOWN_APPS[@]} -gt 0 ]; then",
                '    COMBINED+=("${UNKNOWN_APPS[@]}")',
                "fi",
                "if [ ${#COMBINED[@]} -eq 0 ]; then",
                '    echo "<result>NOT_FOUND</result>"',
                "else",
                "    OUT=$(printf \"%s\\n\" \"${COMBINED[@]}\" | /usr/bin/awk 'NF' | /usr/bin/paste -sd ';' -)",
                '    echo "<result>$OUT</result>"',
                "fi",
            ]
        )
    else:
        lines.extend(
            [
                "EXIT_CODE=0",
                "",
                "if [ ${#RESULTS[@]} -gt 0 ]; then",
                '    echo "ALERT: ${#RESULTS[@]} cataloged indicator(s) found:"',
                '    for item in "${RESULTS[@]}"; do',
                '        echo "  - $item"',
                "    done",
                "    EXIT_CODE=1",
                "fi",
                "",
                "if [ ${#UNKNOWN_APPS[@]} -gt 0 ]; then",
                '    echo ""',
                '    echo "INVENTORY: ${#UNKNOWN_APPS[@]} uncataloged application(s) discovered:"',
                '    for item in "${UNKNOWN_APPS[@]}"; do',
                '        echo "  - $item"',
                "    done",
                "fi",
                "",
                "if [ ${#RESULTS[@]} -eq 0 ] && [ ${#UNKNOWN_APPS[@]} -eq 0 ]; then",
                '    echo "CLEAN: No monitored apps detected and no uncataloged apps found."',
                "fi",
                "",
                "exit $EXIT_CODE",
            ]
        )

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Jamf/MDM host scan script")
    parser.add_argument(
        "--min-status",
        default="validated",
        choices=["draft", "reviewed", "validated"],
        help="Minimum IOC status to include (default: validated)",
    )
    parser.add_argument(
        "--category", default=None, help="Only include apps in the given category"
    )
    parser.add_argument(
        "--output-mode",
        default="report",
        choices=["report", "jamf_ea"],
        help="Rendered script output mode (default: report)",
    )
    args = parser.parse_args()

    apps = load_apps(args.min_status, args.category)
    if not apps:
        suffix = f" in category '{args.category}'" if args.category else ""
        print(
            f"# No apps meet min-status '{args.min_status}'{suffix}. No scan generated.",
            file=sys.stderr,
        )
        sys.exit(0)

    output = generate_scan_script(
        apps,
        args.min_status,
        args.category,
        output_mode=args.output_mode,
    )
    sys.stdout.write(output)


if __name__ == "__main__":
    main()
