#!/usr/bin/env python3
"""Generate Jamf/MDM host scanning script from app YAML files.

Only includes apps whose host IOC group meets the --min-status threshold.
Optionally filters to a specific app category.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date

from app_control.catalog import filter_apps_with_ioc_group

GENERIC_DIR_NAMES = {
    "app", "api", "bin", "build", "client", "config", "configs", "data",
    "developer", "dist", "docs", "frontend", "lib", "log", "logs", "output",
    "server", "src", "web",
}

# User-relative bin prefixes that imply a system-wide install may also exist.
_USER_BIN_PREFIXES = (".local/bin/", ".cargo/bin/")
# Common system-wide bin directories to check for the same binary name.
_SYSTEM_BIN_DIRS = ("/opt/homebrew/bin", "/usr/local/bin")


def load_apps(min_status: str, category: str | None = None) -> list[dict]:
    return filter_apps_with_ioc_group("host", min_status=min_status, category=category)


def shell_escape(value: str) -> str:
    return value.replace("'", "'\\''")


def classify_path(path: str) -> tuple[str, str]:
    """Classify an IOC path into a scan strategy.

    Returns (category, normalized_value) where category is one of:
      user     – path relative to a user home directory
      system   – absolute path to check directly
      repo     – repo-clone directory to search in SEARCH_DIRS
      project  – project-level artifact to find in SEARCH_DIRS
    """
    if path.startswith("~/") or path.startswith("$HOME/") or path.startswith("${HOME}/"):
        normalized = path.replace("~/", "").replace("$HOME/", "").replace("${HOME}/", "")
        return "user", normalized

    if path.startswith("/"):
        return "system", path

    if path.startswith("*/"):
        inner = path[2:]
        first_component = inner.split("/")[0]
        if first_component and first_component.lower() not in GENERIC_DIR_NAMES and not first_component.startswith("."):
            return "repo", inner
        return "project", inner

    if path.startswith("./"):
        return "project", path[2:]

    if path.startswith("*"):
        return "project", path

    return "project", path


def generate_scan_script(apps: list[dict], min_status: str, category: str | None = None) -> str:
    lines: list[str] = []

    # --- header ---
    lines.append("#!/bin/bash")
    lines.append(f"# Auto-generated by jamf_scan.py on {date.today().isoformat()}")
    lines.append(f"# Minimum IOC status: {min_status}")
    if category:
        lines.append(f"# Category filter: {category}")
    lines.append(f"# Apps scanned: {len(apps)}")
    lines.append("")
    lines.append("set -euo pipefail")
    lines.append("")
    lines.append("FOUND_APPS=()")
    lines.append("")

    # --- enumerate user homes ---
    lines.append("USER_HOMES=()")
    lines.append("for h in /Users/*; do")
    lines.append('    [ -d "$h" ] || continue')
    lines.append('    [ "$h" = "/Users/Shared" ] && continue')
    lines.append('    USER_HOMES+=("$h")')
    lines.append("done")
    lines.append("")

    # --- common directories where repos/projects may live ---
    lines.append("SEARCH_DIRS=()")
    lines.append('for h in "${USER_HOMES[@]}"; do')
    lines.append(
        "    for sub in Documents Desktop Downloads"
        " code Code repos projects src git workspace dev Development; do"
    )
    lines.append('        [ -d "$h/$sub" ] && SEARCH_DIRS+=("$h/$sub")')
    lines.append("    done")
    lines.append('    SEARCH_DIRS+=("$h")')
    lines.append("done")
    lines.append("")

    # --- helper functions ---
    lines.append("check_app() {")
    lines.append('    local app_id="$1"; shift')
    lines.append('    for candidate in "$@"; do')
    lines.append('        if [ -e "$candidate" ]; then')
    lines.append('            FOUND_APPS+=("$app_id:$candidate")')
    lines.append("        fi")
    lines.append("    done")
    lines.append("}")
    lines.append("")

    lines.append("search_dirs() {")
    lines.append('    local app_id="$1"')
    lines.append('    local rel_path="$2"')
    lines.append('    for d in "${SEARCH_DIRS[@]}"; do')
    lines.append('        if [ -e "$d/$rel_path" ]; then')
    lines.append('            FOUND_APPS+=("$app_id:$d/$rel_path")')
    lines.append("            return")
    lines.append("        fi")
    lines.append("    done")
    lines.append("}")
    lines.append("")

    lines.append("search_name() {")
    lines.append('    local app_id="$1"')
    lines.append('    local pattern="$2"')
    lines.append('    local type_flag="${3:--d}"')
    lines.append('    for d in "${SEARCH_DIRS[@]}"; do')
    lines.append("        local match")
    lines.append(
        '        match=$(find "$d" -maxdepth 3 "$type_flag" -name "$pattern" -print -quit 2>/dev/null)'
    )
    lines.append('        if [ -n "$match" ]; then')
    lines.append('            FOUND_APPS+=("$app_id:$match")')
    lines.append("            return")
    lines.append("        fi")
    lines.append("    done")
    lines.append("}")
    lines.append("")

    # --- per-app scan blocks ---
    for app in apps:
        app_id = app["id"]
        app_name = app["name"]
        host = app["iocs"]["host"]
        var_name = app_id.upper().replace("-", "_").replace(".", "_")
        if var_name[0].isdigit():
            var_name = "APP_" + var_name

        system_paths: list[str] = []
        user_paths: list[str] = []
        repo_paths: list[str] = []
        project_paths: list[str] = []

        for path in host.get("paths", []):
            cat, val = classify_path(path)
            if cat == "system":
                system_paths.append(val)
            elif cat == "user":
                user_paths.append(val)
            elif cat == "repo":
                repo_paths.append(val)
            else:
                project_paths.append(val)

        # Auto-infer common system-wide bin paths from user bin paths.
        system_set = set(system_paths)
        for up in user_paths:
            for prefix in _USER_BIN_PREFIXES:
                if up.startswith(prefix):
                    binary = up[len(prefix):]
                    for sdir in _SYSTEM_BIN_DIRS:
                        candidate = f"{sdir}/{binary}"
                        if candidate not in system_set:
                            system_paths.append(candidate)
                            system_set.add(candidate)
                    break

        has_candidates = bool(system_paths or user_paths)
        has_searches = bool(repo_paths or project_paths)
        has_processes = bool(host.get("process_names"))
        has_bundles = bool(host.get("bundle_ids"))

        if not (has_candidates or has_searches or has_processes or has_bundles):
            continue

        lines.append(f"# {'─' * 30}")
        lines.append(f"# {app_name} ({app_id})")
        lines.append(f"# {'─' * 30}")

        # static candidates (system + user-relative)
        if has_candidates:
            lines.append(f"{var_name}_CANDIDATES=(")
            for sp in system_paths:
                lines.append(f'    "{shell_escape(sp)}"')
            lines.append(")")
            lines.append("")

            if user_paths:
                lines.append('for h in "${USER_HOMES[@]}"; do')
                lines.append(f"    {var_name}_CANDIDATES+=(")
                for up in user_paths:
                    lines.append(f'        "$h/{shell_escape(up)}"')
                lines.append("    )")
                lines.append("done")
                lines.append("")

            lines.append(f'check_app "{app_id}" "${{{var_name}_CANDIDATES[@]}}"')
            lines.append("")

        # repo-clone searches
        for rp in repo_paths:
            lines.append(f'search_dirs "{app_id}" "{shell_escape(rp)}"')

        # project-level artifact searches
        for pp in project_paths:
            name = pp.rstrip("/").split("/")[0]
            if name.startswith("*"):
                type_flag = "-d" if pp.endswith("/") else "-f"
                lines.append(f'search_name "{app_id}" "{shell_escape(name)}" {type_flag}')
            elif "/" not in pp.rstrip("/"):
                type_flag = "-d" if pp.endswith("/") else "-f"
                lines.append(f'search_name "{app_id}" "{shell_escape(name)}" {type_flag}')
            else:
                parts = pp.rstrip("/").split("/")
                distinctive = next(
                    (p for p in parts if p.lower() not in GENERIC_DIR_NAMES and p != "."),
                    parts[-1],
                )
                is_terminal = distinctive == parts[-1]
                if is_terminal:
                    type_flag = "-d" if pp.endswith("/") else "-f"
                else:
                    type_flag = "-d"
                lines.append(f'search_name "{app_id}" "{shell_escape(distinctive)}" {type_flag}')

        if has_searches:
            lines.append("")

        # process checks
        for process_name in host.get("process_names", []):
            lines.append(f'if pgrep -x "{shell_escape(process_name)}" > /dev/null 2>&1; then')
            lines.append(f'    FOUND_APPS+=("{app_id}:process:{process_name}")')
            lines.append("fi")
        if has_processes:
            lines.append("")

        # bundle-id checks
        for bundle_id in host.get("bundle_ids", []):
            lines.append(
                f'if mdfind "kMDItemCFBundleIdentifier == \'{shell_escape(bundle_id)}\'" '
                f"2>/dev/null | head -1 | grep -q .; then"
            )
            lines.append(f'    FOUND_APPS+=("{app_id}:bundle:{bundle_id}")')
            lines.append("fi")
        if has_bundles:
            lines.append("")

    # --- report ---
    lines.append("# --- Report ---")
    lines.append('if [ ${#FOUND_APPS[@]} -eq 0 ]; then')
    lines.append('    echo "CLEAN: No monitored apps detected."')
    lines.append('    exit 0')
    lines.append("fi")
    lines.append("")
    lines.append('echo "ALERT: ${#FOUND_APPS[@]} indicator(s) found:"')
    lines.append('for item in "${FOUND_APPS[@]}"; do')
    lines.append('    echo "  - $item"')
    lines.append("done")
    lines.append("exit 1")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Jamf/MDM host scan script")
    parser.add_argument(
        "--min-status",
        default="validated",
        choices=["draft", "reviewed", "validated"],
        help="Minimum IOC status to include (default: validated)",
    )
    parser.add_argument("--category", default=None, help="Only include apps in the given category")
    args = parser.parse_args()

    apps = load_apps(args.min_status, args.category)
    if not apps:
        suffix = f" in category '{args.category}'" if args.category else ""
        print(
            f"# No apps meet min-status '{args.min_status}'{suffix}. No scan generated.",
            file=sys.stderr,
        )
        sys.exit(0)

    output = generate_scan_script(apps, args.min_status, args.category)
    sys.stdout.write(output)


if __name__ == "__main__":
    main()
